# Generated by Django 3.1.1 on 2020-09-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名前')),
                ('birthday', models.DateTimeField(verbose_name='誕生日')),
                ('height', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='身長')),
                ('weight', models.IntegerField(verbose_name='体重')),
                ('blood_type', models.CharField(max_length=50, verbose_name='血液型')),
            ],
        ),
    ]
