# Generated by Django 3.1.1 on 2020-09-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earth', '0002_auto_20200903_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='blood_type',
            field=models.CharField(choices=[('A', 'A型'), ('B', 'B型'), ('O', 'O型'), ('AB', 'AB型')], max_length=50, verbose_name='血液型'),
        ),
    ]
